/**
 * Training methods with hard requirement objects.
 */

import type { SkillId } from "../xp";
import {
  type Requirement,
  type RegionTag,
  SkillReq,
  RegionReq,
  AnyRegionReq,
  AllReq,
  AnyReq,
  FlagReq,
  INVENTION_UNLOCK,
  ANCIENT_INVENTION_UNLOCK,
} from "./requirements";

export type Intensity = "afk" | "semi" | "clicky" | "tick";

export interface TrainMethod {
  id: string;
  name: string;
  skill: SkillId;
  minLevel: number;
  maxLevel: number;
  /** Main-game peak base XP/hr before league mult */
  baseXpPerHour: number;
  alsoTrains?: Partial<Record<SkillId, number>>;
  intensity: Intensity;
  priority: number;
  /** Hard gates — ALL must pass (compose with AllReq/AnyReq inside) */
  requires: Requirement;
  notes?: string;
  passive?: boolean;
  /** Soft tags for filtering */
  tags?: string[];
}

function freeOr(...regions: RegionTag[]): Requirement {
  return new AnyRegionReq(["free", "misthalin", "havenhythe", "karamja", ...regions]);
}

function alwaysFree(): Requirement {
  return new AnyRegionReq(["free", "misthalin", "havenhythe", "karamja"]);
}

/**
 * Curated methods. Invention methods HARD-require Asgarnia + 80s.
 * Ancient Invention is a separate unlock (Kandarin), not an XP method —
 * but ancient gizmo crafting can be a tagged late method.
 */
export const TRAIN_METHODS: TrainMethod[] = [
  // Combat
  {
    id: "cbt-low",
    name: "Low combat (chickens / cows / goblins)",
    skill: "attack",
    minLevel: 1,
    maxLevel: 30,
    baseXpPerHour: 25_000,
    alsoTrains: { strength: 1, defence: 0.4, constitution: 0.35 },
    intensity: "afk",
    priority: 10,
    requires: alwaysFree(),
  },
  {
    id: "cbt-slayer-early",
    name: "Early free-region Slayer",
    skill: "attack",
    minLevel: 30,
    maxLevel: 60,
    baseXpPerHour: 80_000,
    alsoTrains: { strength: 1, defence: 0.5, constitution: 0.4, slayer: 0.35 },
    intensity: "semi",
    priority: 5,
    requires: alwaysFree(),
  },
  {
    id: "cbt-slayer-mid",
    name: "Mid Slayer + AOE",
    skill: "attack",
    minLevel: 60,
    maxLevel: 90,
    baseXpPerHour: 220_000,
    alsoTrains: { strength: 1, defence: 0.55, constitution: 0.45, slayer: 0.4 },
    intensity: "semi",
    priority: 3,
    requires: freeOr("asgarnia", "desert", "morytania"),
  },
  {
    id: "cbt-slayer-late",
    name: "High Slayer / reaper / ED trash",
    skill: "attack",
    minLevel: 90,
    maxLevel: 99,
    baseXpPerHour: 450_000,
    alsoTrains: { strength: 1, defence: 0.5, constitution: 0.45, slayer: 0.35 },
    intensity: "semi",
    priority: 2,
    requires: freeOr("asgarnia", "desert", "forinthry"),
  },
  {
    id: "slayer-120",
    name: "Elite Slayer / reaper camp",
    skill: "slayer",
    minLevel: 99,
    maxLevel: 120,
    baseXpPerHour: 200_000,
    alsoTrains: { attack: 0.5, strength: 0.5, constitution: 0.3 },
    intensity: "semi",
    priority: 2,
    requires: freeOr("asgarnia", "desert", "forinthry", "morytania"),
  },
  {
    id: "cbt-revo",
    name: "Revolution combat camp",
    skill: "strength",
    minLevel: 50,
    maxLevel: 99,
    baseXpPerHour: 350_000,
    alsoTrains: { attack: 0.9, defence: 0.5, constitution: 0.4 },
    intensity: "afk",
    priority: 8,
    requires: alwaysFree(),
  },
  {
    id: "rng-early",
    name: "Early ranged combat",
    skill: "ranged",
    minLevel: 1,
    maxLevel: 40,
    baseXpPerHour: 40_000,
    alsoTrains: { defence: 0.2, constitution: 0.3 },
    intensity: "afk",
    priority: 6,
    requires: alwaysFree(),
  },
  {
    id: "rng-slayer",
    name: "Ranged Slayer / packs",
    skill: "ranged",
    minLevel: 40,
    maxLevel: 99,
    baseXpPerHour: 400_000,
    alsoTrains: { defence: 0.3, constitution: 0.4, slayer: 0.3 },
    intensity: "semi",
    priority: 4,
    requires: freeOr("tirannwn", "kandarin"),
  },
  {
    id: "mage-early",
    name: "Early magic combat",
    skill: "magic",
    minLevel: 1,
    maxLevel: 40,
    baseXpPerHour: 35_000,
    alsoTrains: { defence: 0.15, constitution: 0.25 },
    intensity: "afk",
    priority: 6,
    requires: alwaysFree(),
  },
  {
    id: "mage-combat",
    name: "Magic combat / burst",
    skill: "magic",
    minLevel: 40,
    maxLevel: 99,
    baseXpPerHour: 380_000,
    alsoTrains: { defence: 0.3, constitution: 0.4 },
    intensity: "semi",
    priority: 4,
    requires: freeOr("asgarnia", "desert"),
  },
  {
    id: "necro-early",
    name: "Necro quests + ritual ladder",
    skill: "necromancy",
    minLevel: 1,
    maxLevel: 60,
    baseXpPerHour: 120_000,
    intensity: "semi",
    priority: 1,
    requires: alwaysFree(),
    notes: "Misthalin free — City of Um path",
  },
  {
    id: "necro-rituals",
    name: "Efficient rituals",
    skill: "necromancy",
    minLevel: 20,
    maxLevel: 90,
    baseXpPerHour: 500_000,
    intensity: "semi",
    priority: 2,
    requires: alwaysFree(),
  },
  {
    id: "necro-combat",
    name: "Necro combat / Rasial",
    skill: "necromancy",
    minLevel: 70,
    maxLevel: 120,
    baseXpPerHour: 600_000,
    alsoTrains: { constitution: 0.35, defence: 0.25 },
    intensity: "semi",
    priority: 1,
    requires: alwaysFree(),
    notes: "Omni + lantern grind",
  },
  {
    id: "prayer-bones",
    name: "Bones on altar",
    skill: "prayer",
    minLevel: 1,
    maxLevel: 70,
    baseXpPerHour: 400_000,
    intensity: "clicky",
    priority: 3,
    requires: freeOr("asgarnia"),
  },
  {
    id: "prayer-powder",
    name: "Powder of burials / high bones",
    skill: "prayer",
    minLevel: 70,
    maxLevel: 99,
    baseXpPerHour: 1_200_000,
    intensity: "clicky",
    priority: 2,
    requires: freeOr("asgarnia"),
  },
  {
    id: "summ-pouches",
    name: "Charm pouches",
    skill: "summoning",
    minLevel: 1,
    maxLevel: 99,
    baseXpPerHour: 800_000,
    intensity: "semi",
    priority: 3,
    requires: freeOr("asgarnia", "karamja"),
    notes: "Obelisk access — Taverley is Asgarnia; some free options exist",
  },

  // Gathering
  {
    id: "mine-early",
    name: "Copper/tin → iron",
    skill: "mining",
    minLevel: 1,
    maxLevel: 30,
    baseXpPerHour: 30_000,
    intensity: "afk",
    priority: 5,
    requires: alwaysFree(),
  },
  {
    id: "mine-mid",
    name: "Coal / mithril",
    skill: "mining",
    minLevel: 30,
    maxLevel: 70,
    baseXpPerHour: 80_000,
    intensity: "afk",
    priority: 4,
    requires: freeOr("asgarnia", "fremennik"),
  },
  {
    id: "mine-high",
    name: "Orthen / high rocks",
    skill: "mining",
    minLevel: 70,
    maxLevel: 110,
    baseXpPerHour: 250_000,
    intensity: "semi",
    priority: 2,
    requires: freeOr("anachronia", "asgarnia"),
  },
  {
    id: "mine-primal",
    name: "Primal / best ore",
    skill: "mining",
    minLevel: 90,
    maxLevel: 110,
    baseXpPerHour: 400_000,
    intensity: "semi",
    priority: 1,
    requires: freeOr("anachronia", "forinthry", "asgarnia"),
  },
  {
    id: "wc-early",
    name: "Trees → willows",
    skill: "woodcutting",
    minLevel: 1,
    maxLevel: 40,
    baseXpPerHour: 40_000,
    intensity: "afk",
    priority: 5,
    requires: alwaysFree(),
  },
  {
    id: "wc-mid",
    name: "Maples / yews / magic",
    skill: "woodcutting",
    minLevel: 40,
    maxLevel: 80,
    baseXpPerHour: 120_000,
    intensity: "afk",
    priority: 3,
    requires: freeOr("kandarin", "tirannwn"),
  },
  {
    id: "wc-high",
    name: "Crystal / best trees",
    skill: "woodcutting",
    minLevel: 80,
    maxLevel: 110,
    baseXpPerHour: 300_000,
    intensity: "semi",
    priority: 2,
    requires: freeOr("tirannwn", "anachronia", "kandarin"),
  },
  {
    id: "fish-early",
    name: "Shrimp → trout/salmon",
    skill: "fishing",
    minLevel: 1,
    maxLevel: 40,
    baseXpPerHour: 35_000,
    intensity: "afk",
    priority: 5,
    requires: alwaysFree(),
  },
  {
    id: "fish-mid",
    name: "Lobs → sharks",
    skill: "fishing",
    minLevel: 40,
    maxLevel: 80,
    baseXpPerHour: 90_000,
    intensity: "afk",
    priority: 3,
    requires: freeOr("karamja", "fremennik", "asgarnia"),
  },
  {
    id: "fish-high",
    name: "Swarm / deep sea (if unlocked)",
    skill: "fishing",
    minLevel: 80,
    maxLevel: 99,
    baseXpPerHour: 250_000,
    intensity: "semi",
    priority: 2,
    requires: freeOr("kandarin", "anachronia", "fremennik", "asgarnia"),
    notes: "Deep Sea Fishing is Kandarin; LRC fish is Asgarnia",
  },
  {
    id: "hunt-early",
    name: "Bird snares → deadfall",
    skill: "hunter",
    minLevel: 1,
    maxLevel: 50,
    baseXpPerHour: 50_000,
    intensity: "semi",
    priority: 4,
    requires: freeOr("karamja"),
  },
  {
    id: "hunt-mid",
    name: "Box traps mid",
    skill: "hunter",
    minLevel: 50,
    maxLevel: 80,
    baseXpPerHour: 180_000,
    intensity: "semi",
    priority: 3,
    requires: freeOr("tirannwn", "anachronia", "kandarin"),
  },
  {
    id: "hunt-high",
    name: "Best Hunter / BGH-style",
    skill: "hunter",
    minLevel: 80,
    maxLevel: 99,
    baseXpPerHour: 400_000,
    intensity: "semi",
    priority: 2,
    requires: freeOr("anachronia", "havenhythe"),
  },
  {
    id: "farm-runs",
    name: "Herb + tree runs",
    skill: "farming",
    minLevel: 1,
    maxLevel: 120,
    baseXpPerHour: 150_000,
    intensity: "semi",
    priority: 1,
    requires: alwaysFree(),
    passive: true,
    notes: "5× grow speed league passive — patches in free regions exist",
  },
  {
    id: "div-early",
    name: "Wisps ladder",
    skill: "divination",
    minLevel: 1,
    maxLevel: 70,
    baseXpPerHour: 60_000,
    intensity: "afk",
    priority: 4,
    requires: alwaysFree(),
  },
  {
    id: "div-high",
    name: "Incandescent / best wisp",
    skill: "divination",
    minLevel: 70,
    maxLevel: 99,
    baseXpPerHour: 200_000,
    intensity: "semi",
    priority: 2,
    requires: freeOr("asgarnia"),
  },
  {
    id: "arch-early",
    name: "Arch Guild + early sites (free)",
    skill: "archaeology",
    minLevel: 1,
    maxLevel: 70,
    baseXpPerHour: 100_000,
    intensity: "semi",
    priority: 2,
    requires: alwaysFree(),
    notes: "Archaeology Guild = Varrock / Misthalin free",
  },
  {
    id: "arch-mid",
    name: "Mid dig sites (region-dependent)",
    skill: "archaeology",
    minLevel: 70,
    maxLevel: 95,
    baseXpPerHour: 250_000,
    intensity: "semi",
    priority: 2,
    requires: freeOr("desert", "asgarnia", "kandarin", "anachronia"),
    notes: "Kharid-et=Desert; Warforge/Stormguard=Kandarin",
  },
  {
    id: "arch-stormguard",
    name: "Stormguard Citadel excavation",
    skill: "archaeology",
    minLevel: 70,
    maxLevel: 120,
    baseXpPerHour: 350_000,
    intensity: "semi",
    priority: 1,
    requires: new AllReq([
      new RegionReq("kandarin"),
      new SkillReq("archaeology", 70),
    ]),
    notes: "REQUIRED region for Ancient Invention blueprints path",
    tags: ["stormguard", "ancient-invention-path"],
  },
  {
    id: "arch-high-other",
    name: "High-tier non-Stormguard sites",
    skill: "archaeology",
    minLevel: 90,
    maxLevel: 120,
    baseXpPerHour: 320_000,
    intensity: "semi",
    priority: 2,
    requires: freeOr("desert", "anachronia", "asgarnia"),
  },

  // Artisan
  {
    id: "cook-early",
    name: "Cook fish ladder",
    skill: "cooking",
    minLevel: 1,
    maxLevel: 80,
    baseXpPerHour: 200_000,
    intensity: "afk",
    priority: 3,
    requires: alwaysFree(),
  },
  {
    id: "cook-high",
    name: "High fish / rocktails",
    skill: "cooking",
    minLevel: 80,
    maxLevel: 99,
    baseXpPerHour: 450_000,
    intensity: "afk",
    priority: 2,
    requires: freeOr("asgarnia", "fremennik"),
  },
  {
    id: "fm-logs",
    name: "Burn logs",
    skill: "firemaking",
    minLevel: 1,
    maxLevel: 90,
    baseXpPerHour: 300_000,
    intensity: "semi",
    priority: 3,
    requires: alwaysFree(),
  },
  {
    id: "fm-high",
    name: "Incinerator / high FM",
    skill: "firemaking",
    minLevel: 90,
    maxLevel: 99,
    baseXpPerHour: 700_000,
    intensity: "clicky",
    priority: 2,
    requires: freeOr("asgarnia"),
  },
  {
    id: "craft-early",
    name: "Leather / jewellery",
    skill: "crafting",
    minLevel: 1,
    maxLevel: 60,
    baseXpPerHour: 80_000,
    intensity: "semi",
    priority: 4,
    requires: alwaysFree(),
  },
  {
    id: "craft-guild",
    name: "Crafting Guild methods",
    skill: "crafting",
    minLevel: 40,
    maxLevel: 99,
    baseXpPerHour: 280_000,
    intensity: "semi",
    priority: 3,
    requires: new RegionReq("asgarnia"),
    notes: "Crafting Guild = Asgarnia",
  },
  {
    id: "craft-high",
    name: "Urns / glass / high craft",
    skill: "crafting",
    minLevel: 60,
    maxLevel: 99,
    baseXpPerHour: 350_000,
    intensity: "semi",
    priority: 2,
    requires: freeOr("asgarnia"),
  },
  {
    id: "fletch-early",
    name: "Arrows / bows",
    skill: "fletching",
    minLevel: 1,
    maxLevel: 70,
    baseXpPerHour: 150_000,
    intensity: "afk",
    priority: 3,
    requires: alwaysFree(),
  },
  {
    id: "fletch-high",
    name: "Broad arrows / high fletch",
    skill: "fletching",
    minLevel: 70,
    maxLevel: 99,
    baseXpPerHour: 600_000,
    intensity: "afk",
    priority: 2,
    requires: alwaysFree(),
  },
  {
    id: "smith-early",
    name: "Bronze → steel",
    skill: "smithing",
    minLevel: 1,
    maxLevel: 50,
    baseXpPerHour: 80_000,
    intensity: "semi",
    priority: 4,
    requires: alwaysFree(),
  },
  {
    id: "smith-artisans",
    name: "Artisans' Workshop",
    skill: "smithing",
    minLevel: 30,
    maxLevel: 99,
    baseXpPerHour: 350_000,
    intensity: "semi",
    priority: 2,
    requires: new RegionReq("asgarnia"),
    notes: "Artisans' Workshop = Falador / Asgarnia",
  },
  {
    id: "smith-burial",
    name: "Corrupted / burial smithing",
    skill: "smithing",
    minLevel: 70,
    maxLevel: 110,
    baseXpPerHour: 500_000,
    intensity: "semi",
    priority: 1,
    requires: freeOr("asgarnia", "kandarin"),
    notes: "Burial anvil also at Warforge (Kandarin)",
  },
  {
    id: "herb-early",
    name: "Clean herbs + early potions",
    skill: "herblore",
    minLevel: 1,
    maxLevel: 70,
    baseXpPerHour: 200_000,
    intensity: "clicky",
    priority: 3,
    requires: alwaysFree(),
  },
  {
    id: "herb-ovl",
    name: "Overloads / combos",
    skill: "herblore",
    minLevel: 70,
    maxLevel: 120,
    baseXpPerHour: 800_000,
    intensity: "clicky",
    priority: 1,
    requires: alwaysFree(),
    notes: "Supply-gated more than region-gated",
  },
  {
    id: "rc-early",
    name: "Air → elemental RC",
    skill: "runecrafting",
    minLevel: 1,
    maxLevel: 70,
    baseXpPerHour: 50_000,
    intensity: "semi",
    priority: 5,
    requires: alwaysFree(),
  },
  {
    id: "rc-ourania",
    name: "Ourania / abyss RC",
    skill: "runecrafting",
    minLevel: 70,
    maxLevel: 110,
    baseXpPerHour: 250_000,
    intensity: "clicky",
    priority: 2,
    requires: freeOr("kandarin", "asgarnia", "forinthry"),
    notes: "Ourania = Kandarin; some altars free/Asgarnia",
  },
  {
    id: "con-planks",
    name: "Planks + flatpacks",
    skill: "construction",
    minLevel: 1,
    maxLevel: 99,
    baseXpPerHour: 500_000,
    intensity: "clicky",
    priority: 2,
    requires: freeOr("asgarnia"),
  },
  {
    id: "agi-early",
    name: "Gnome / Draynor / Varrock",
    skill: "agility",
    minLevel: 1,
    maxLevel: 50,
    baseXpPerHour: 30_000,
    intensity: "clicky",
    priority: 4,
    requires: alwaysFree(),
  },
  {
    id: "agi-advanced",
    name: "Advanced courses",
    skill: "agility",
    minLevel: 50,
    maxLevel: 99,
    baseXpPerHour: 120_000,
    intensity: "clicky",
    priority: 2,
    requires: freeOr("anachronia", "tirannwn", "asgarnia", "kandarin"),
  },
  {
    id: "thieve-early",
    name: "Pickpocket / stalls",
    skill: "thieving",
    minLevel: 1,
    maxLevel: 50,
    baseXpPerHour: 40_000,
    intensity: "semi",
    priority: 4,
    requires: alwaysFree(),
  },
  {
    id: "thieve-high",
    name: "Safecracking / dwarves",
    skill: "thieving",
    minLevel: 50,
    maxLevel: 99,
    baseXpPerHour: 350_000,
    intensity: "semi",
    priority: 2,
    requires: freeOr("asgarnia", "fremennik", "kandarin"),
  },
  {
    id: "dg-floors",
    name: "DG floors / ED / sinkholes",
    skill: "dungeoneering",
    minLevel: 1,
    maxLevel: 120,
    baseXpPerHour: 400_000,
    intensity: "semi",
    priority: 2,
    requires: alwaysFree(),
    notes: "Daemonheim (Forinthry) optional; ED/sinkholes + DG shop outside Wildy",
  },

  // ── INVENTION (hard gated) ─────────────────────────────────────────
  {
    id: "inv-disassemble",
    name: "Disassemble + siphon (standard Invention)",
    skill: "invention",
    minLevel: 1,
    maxLevel: 120,
    baseXpPerHour: 300_000,
    intensity: "semi",
    priority: 2,
    requires: INVENTION_UNLOCK,
    notes:
      "HARD: 80 Craft+Smith+Div (unboostable) AND Asgarnia (Invention Guild). Tutorial auto-completes in league once met. Does NOT require Ancient Invention.",
    tags: ["invention"],
  },
  {
    id: "inv-machines",
    name: "Invention machines (guild)",
    skill: "invention",
    minLevel: 20,
    maxLevel: 120,
    baseXpPerHour: 280_000,
    intensity: "afk",
    priority: 3,
    requires: INVENTION_UNLOCK,
    notes: "Guild machines — Asgarnia only",
    tags: ["invention"],
  },
  {
    id: "inv-ancient-gizmos",
    name: "Ancient gizmo discovery / crafting XP",
    skill: "invention",
    minLevel: 85,
    maxLevel: 120,
    baseXpPerHour: 350_000,
    intensity: "semi",
    priority: 1,
    requires: ANCIENT_INVENTION_UNLOCK,
    notes:
      "HARD: Ancient Invention = Kandarin Stormguard + 85 Inv + 95 Arch + Howl's workshop. Better perks, not required for raw Inv levels.",
    tags: ["invention", "ancient-invention"],
  },
];

export function xpForSkill(m: TrainMethod, skill: SkillId): number {
  if (m.skill === skill) return m.baseXpPerHour;
  const f = m.alsoTrains?.[skill];
  return f ? m.baseXpPerHour * f : 0;
}
